### ISSUE TITLE
Code from Readme crashes

### ISSUE THREAD

**Issue by matkoniecz** [RustyRin/bandcamp-api#13]
tried running https://github.com/RustyRin/bandcamp-api#basic-use

```
Traceback (most recent call last):
  File "/home/mateusz/Desktop/tmp/test.py", line 5, in <module>
    album = bc.get_album(album_url="https://c418.bandcamp.com/album/minecraft-volume-alpha")
  File "/home/mateusz/.local/lib/python3.10/site-packages/bandcamp_api/bandcamp_api.py", line 65, in get_album
    return Album(album_id=item.album_id, artist_id=item.artist_id, advanced=advanced)
  File "/home/mateusz/.local/lib/python3.10/site-packages/bandcamp_api/album.py", line 197, in __init__
    self.tracks.append(Track(artist_id=self.artist_id, track_id=track['track_id'], advanced=advanced))
  File "/home/mateusz/.local/lib/python3.10/site-packages/bandcamp_api/track.py", line 98, in __init__
    self.track_streamable_url = result['file']['mp3-128']
KeyError: 'file'
```

Python 3.10.13

bandcamp_api              0.2.3 (weird - https://github.com/RustyRin/bandcamp-api/blob/main/setup.py has 0.2.2 as latest?)

but...

```
Defaulting to user installation because normal site-packages is not writeable
Collecting bandcamp_api
  Downloading bandcamp_api-0.2.3.tar.gz (25 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: setuptools in /home/mateusz/.local/lib/python3.10/site-packages (from bandcamp_api) (69.0.3)
Requirement already satisfied: beautifulsoup4 in /usr/lib/python3/dist-packages (from bandcamp_api) (4.8.2)
Collecting demjson3 (from bandcamp_api)
  Downloading demjson3-3.0.6.tar.gz (131 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.5/131.5 kB 2.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: html5lib in /usr/lib/python3/dist-packages (from bandcamp_api) (1.0.1)
Requirement already satisfied: lxml in /home/mateusz/.local/lib/python3.10/site-packages (from bandcamp_api) (4.9.3)
Requirement already satisfied: requests in /home/mateusz/.local/lib/python3.10/site-packages (from bandcamp_api) (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/mateusz/.local/lib/python3.10/site-packages (from requests->bandcamp_api) (3.0.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests->bandcamp_api) (2.8)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/mateusz/.local/lib/python3.10/site-packages (from requests->bandcamp_api) (2.0.6)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->bandcamp_api) (2019.11.28)
Building wheels for collected packages: bandcamp_api, demjson3
  Building wheel for bandcamp_api (setup.py) ... done
  Created wheel for bandcamp_api: filename=bandcamp_api-0.2.3-py3-none-any.whl size=30142 sha256=8d56e6565fb8f4de27855f302436b649fcc35b389c4b548402665ff8a92736f4
  Stored in directory: /home/mateusz/.cache/pip/wheels/ef/f8/3a/39203c379000ea915425bcc9ce3a8b74c93b18e200911c52bc
  Building wheel for demjson3 (setup.py) ... done
  Created wheel for demjson3: filename=demjson3-3.0.6-py3-none-any.whl size=75280 sha256=46fb34313c16cb662c68f45d1477211aa73bad3e17318a01e6af1226e15169b7
  Stored in directory: /home/mateusz/.cache/pip/wheels/2d/32/af/75c810e14c7ca0df40c20c662fcc7f33d1e055937b4e452cc1
Successfully built bandcamp_api demjson3
Installing collected packages: demjson3, bandcamp_api
Successfully installed bandcamp_api-0.2.3 demjson3-3.0.6
```

**Comment by matkoniecz** [comment]
@RustyRin ping? (obviously you are not obligated to maintain/fix it, but I am wondering is this project still maintained - do you plan to look into it? Would you review PR if I would made it?

I am unsure should I try to fix this code, find another library or write my own)

**Comment by matkoniecz** [comment]
@RustyRin So should I consider this library as abandoned? Would PR be reviewed?

I promise I will not ping in this issue again
