### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find_all' (when no artist is found)

### ISSUE THREAD

**Issue by matkoniecz** [RustyRin/bandcamp-api#2]
```
from bandcamp_api import Bandcamp
bc = Bandcamp()
bc.search_artist("Jacek Kaczmarski")
```

results in 

```
Traceback (most recent call last):
  File "bug.py", line 3, in <module>
    bc.search_artist("Jacek Kaczmarski")
  File "/home/mateusz/.local/lib/python3.8/site-packages/bandcamp_api/bandcamp_api.py", line 123, in search_artist
    return search_artists(search_string=search_string)
  File "/home/mateusz/.local/lib/python3.8/site-packages/bandcamp_api/search.py", line 24, in search_artists
    for item in results.find_all("li"):
AttributeError: 'NoneType' object has no attribute 'find_all'
```

**Comment by RustyRin** [comment]
Dev branch already has this fixed, just uses different objects iirc, will try to put it on main soon ™️

**Comment by RustyRin** [comment]
the fix is now live
